# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-25 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191125_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='isdone',
            new_name='done',
        ),
    ]
